const chatHistory = async (req, res) => {
  const user = req.body.user;
  try {
    const filterHistory = user.chatHistory.map((item, index) => {
      //this loop is to remove the _id field generated by mongoDB
      return {
        role: item.role,
        parts: [{ text: item.parts[0].text }],
      };
    });

    return res.status(200).json(filterHistory ? filterHistory : []);
  } catch (error) {
    console.log(error);
    return res.status(500).json({ message: "Failed to get chat history" });
  }
};

export { chatHistory };
